services:
  - type: web
    name: RR
    env: python 
    buildCommand: pip3 install -U -r requirements.txt  # Build your app (Example: npm install)
    startCommand: python3 bot.py   # Start command for your app (Example: npm start)
    healthCheckPath: /
    env:
      - key: PORT             # Environment variable for port (Example: 8080)
        value: 8080
        
